# Generated by Django 5.2.8 on 2025-12-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TeamDC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_name", models.CharField(max_length=100)),
                ("player_height", models.FloatField(default=0.0)),
                ("player_weight", models.FloatField(default=0.0)),
                ("player_matches_played", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="TeamMarvel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_name", models.CharField(max_length=100)),
                ("player_height", models.FloatField(default=0.0)),
                ("player_weight", models.FloatField(default=0.0)),
                ("player_matches_played", models.IntegerField(default=0)),
            ],
        ),
    ]
